@extends('layouts.frontend')

@section('title')
    <title>Term and Condtions</title>
@stop
@section('content')
    <section class="section">
        <div class="container">
            <p>These General Terms and Conditions set out the terms and conditions  applying to and governing the usage of the CT app - technology which  connects customer with drivers to help them move around cities more  efficiently.</p>
            <p>The term "us" or "we" refers to the owner of the CT app, CARGOATAXI  GMBH, a private limited company, founded in Austria (Company Registration  Number FN 544259 g), whose place of business is Piaristengasse 23, Top  101, 1080 Wien, but also to CARGOATAXI Franchise and partners (local  subsidiaries, representatives, affiliates, agents etc). The list of CT group  companies and partners is available at www.cargotaxi.at.
            </p>
            <p>In order to use CT app you must agree to the terms and conditions that are  set out below:</p>
            <h5>1. Using the CT app</h5>
            <p>1.1 CT provides an information society service through CT app that enables  mediation of the requests for transport services between the Customer and  drivers and CT only provide transport services. Transport services are  provided by drivers under a contract (with you) for the carriage of customer  cargo from 0,5 kg - 10.000 kg. Drivers provide transport services on an  independent basis (either in person or via a company) as economic and  professional service providers. CT is not responsible in any way for the  fulfilment of the contract entered into between the customer (you) and the  driver. Disputes arising from consumer rights, legal obligations or from law  applicable to the provision of transport services will be resolved between the  customer and drivers. Data regarding the drivers and their transport service is  available in the CT app and receipts for journeys are sent to the email address  listed in customers profile. 1.2 . The Customer (you) enters into a contract with  the driver for the provision of transport services via the CT app. Depending on  the payment options supported for given location of the journey, you can  choose whether to pay the driver for the transport service in cash or use CT in-App Payment. Payments for CT Business rides are handled by a separate  agreement for Business journeys. Charges will be inclusive of applicable  taxes where required by law. Charges may include other applicable fees, tolls,  and/or surcharges including a booking fee, municipal tolls, long way deliveries  or processing fees for split payments. If you wish, you may also choose to pay  a Tip to the driver directly or via the use of CT in-App Payment. We may limit  the maximum value of a Tip at our sole discretion. 1.3 During the installation  of CT app, customers mobile number is linked to the respective CT user  account and added to our database. If you are no longer using your mobile  number, you must notify CT within 7 days so we can anonymize your account data. If you do not notify us about any change to your number, your mobile  operator may issue the same mobile number to a new person who when using  the CT app then may have access to your data.
            </p>
            <h5>2. Promotional Codes</h5>
            <p>2.1 CT may send you promotional codes on a per promotion basis.  Promotional code credit can be applied towards payment on completion of a  ride or other features or benefits related to the service and/or a Third Party’s  service and are subject any additional terms that are established on a per  promotional code basis. Expiration dates of promo codes will be reflected in app once you have applied the promo code to your account.  </p>
            <p>2.2 If your trip amount exceeds the redeemable credit allocated to your ride,  the balance will be automatically deducted from your accounts payment  method. Similarly, a promotional code credit only applies on a per ride basis  and cannot carry over to a next ride/ trip and therefore will be forfeited. Only  one promotional code may be applied per trip.  </p>
            <p>2.3 CT reserves the right to cancel any promotional code at any time for any  reason. This includes, but is not limited to, if CT deems that codes are being  used in an unlawful or fraudulent manner, those issued mistakenly, and those  which have expired. </p>
            <h5>3. CARGOTAXI in-App Payment </h5>
            <p>3.1 Depending on the payment options supported for the given location of the  journey, You can pay for the transport services with a card, mobile carrier  billing or other payment methods (e.g: CT Business) as and when available through CT App. By providing CT in-App Payment service, CT acts as  commercial agent for the providers of the transport services. Every driver has  authorised CT as their commercial agent for the mediation of conclusion of  contracts between the driver and the customer, including the power to accept  payments from the custoemr and to forward the payments to the driver. Your  obligation to the provider of the transport service will be fulfilled when the  payment order is given to transfer funds to CT’ bank account. You, as a  customer are responsible for ensuring that the payment takes place and  ensuring that sufficient funds are available.
            </p>
            <p>3.2 You may choose to pay a Tip  to the driver using the CT In-app Payment service. The Tip can be paid via the  In-app Payment by means authorised by CT for that purpose. CT will not hold  a commission for the brokerage of the Tip and the Tip will be transferred to  the driver in full amount, excluding any taxes, if applicable. CT reserves the  right to withhold the Tip, if the payment of the Tip is suspected as being  fraudulent, illegal, for a purpose other than as a gratuity related to the service  provided or used in conflict with CT Terms and Conditions  </p>
            <p>3.3 When making payments by CT in-App Payment, CT receives your  payments and forwards money to the driver. CT may ask additional data from  you to verify payment method.  </p>
            <p>3.4 When making payments by CT in-App Payment for transport services, CT is not responsible for possible third-party payment costs (e.g mobile  operators, bank fees). These service providers may charge you additional  fees when processing payments in connection with the CT in-App Payment.  CT is not responsible for any such fees and disclaims all liability in this regard.  Your payment method may also be subject to additional terms and conditions  imposed by the applicable third-party payment service provider; please review  these terms and conditions before using your payment method.
            </p>
            <p>3.5 CT will be responsible for the functioning of CT in-App Payment and  provide support in resolving problems. The resolution of disputes related to  CT in-App Payment also takes place through us. For payment support service  please contact: office@cargotaxi.eu. Inquiries submitted by e-mail or CT App  will receive a response within one business day. CT will resolve CT in-App  Payment related complaints and applications within two business days. 3.6.  Upfront Fare. You may be offered to use a ride option that allows you to agree  to a fixed Fare for a given instance of Transportation service provided by the  Driver (i.e Upfront Fare). Upfront Fare is communicated to you via the CT App  before the ride is requested. Upfront Fare shall not be applied if you change  the destination during the ride, the ride takes materially longer than estimated  due to traffic or other factors, or when other unexpected circumstances impact  the characteristics of the ride materially (e.g a route is used where tolls apply). </p>
            <h5>4. Ordering and cancelling transport  services</h5>
            <p>4.1 If you order a transport service and the driver has agreed to undertake the  work then the transport service is considered to be ordered.
            </p>
            <p>4.2 Once a driver  confirms that he/she will complete your journey, you will enter into a separate agreement with the driver for the provision of the journey on such terms and  conditions as you agree with the driver. CT does not provide journeys and is  not a party to your agreement with the relevant driver.  </p>
            <p>4.3 Cancelling the use of an ordered transport service is considered to be the  situation where the driver has replied to your request and you subsequently  reject, cancel or refuse the transport service. When a transport service request is cancelled after certain time period you are required to pay a  cancellation fee.  </p>
            <p>4.4 If you cancel a transport service request on multiple successive instances  within 24-hour we may temporarily block your account for warning. After  multiple such warnings, we may suspend your account for longer period (e.g 6  months). After that period you could ask to reactivate your account and your  application will be reviewed by CT. </p>
            <p>4.5 When driver notifies the customwe about the arrival of the vehicle to its  destination and customers or people for whom the transport was ordered do  not arrive at the vehicle within certain time period as specified in the CT app,  the request will be deemed cancelled. Sometimes driver may decide to cancel  your request, please note that CT is not responsible for such situations.  </p>
            <p>4.6 Once the driver arrives and sends you a notification that he/she has  arrived the CT app may begin charging fare on a waiting time basis according  to the rates specified in the CT app.
            </p>
            <p>4.7 If you have requested transport services using the CT app and cause  damage to the driver’s vehicle or its furnishing (among else, by blemishing or  staining the vehicle or causing the vehicle to stink), the driver will have the  right to require you to pay a penalty of 50 EUR and require compensation for  any damages exceeding the penalty. If you do not pay the penalty and/or  compensate the damage, CT may pursue the claims on behalf of the provider  of the transport service.
            </p>
            <h5>5. License to use CARGOTAXI app </h5>
            <p>5.1 As long as you comply with these General Terms and Conditions, we  agree to grant you a royalty free, revocable, non-exclusive, right to access  and use the CT app in accordance with these General Terms and Conditions,  the Privacy Notice and the applicable app-store terms. You may not transfer  or sub-license this right to use the CT app. In the event that your right to use  CT app is cancelled, the corresponding non-exclusive license will also be  cancelled.
            </p>
            <h6>6. Liability</h6>
            <p>6.1 As the CT app is an information society service (a means of  communication) between customer and drivers, we cannot guarantee or take  any responsibility for the quality or the absence of defects in the provision of  transport services. As the usage of CT app for requesting transport services  depends on the behaviour of the drivers, CT does not guarantee that you will  always have offers available for the provision of the transport services.
            </p>
            <p>6.2 The CT app does not offer or broker transport services for customer. It is  also not an transport agency service for finding customer for transport  providers. The CT app is used as the means for organising the provision of  transport services.  </p>
            <p>6.3 The consumer’s right of refund is not applied to CT app orders.  Requesting a refund from the transport service does not withdraw you from  the agreement in the course of which the provision of the transport service  was ordered.
            </p>
            <p>6.4 The CT app is provided on an "as is" and “as available” basis. CT does  not represent, warrant or guarantee that access to CT app will be  uninterrupted or error free. In case of any faults in the software, we will  endeavour to correct them as soon as possible, but please keep in mind that  the functioning of the app may be restricted due to occasional technical errors  and we are not able to guarantee that the app will function at all times, for  example a public emergency may result in a service interruption.  </p>
            <p>6.5 CT, its representatives, directors and employees are not liable for any loss  or damage that you may incur as a result of using CT app or relying on, the  journey contracted for through the CT app, including but not limited to:
            </p>
            <p>6.5.1. any direct or indirect property damage or monetary loss;  </p>
            <p>6.5.2. loss of profit;</p>
            <p>6.5.3. loss of business, contracts, contacts, goodwill, reputation and any loss  that may arise from interruption of the business;</p>
            <p>6.5.4. loss or inaccuracy of data; and </p>
            <p>6.5.5. any other type of loss or damage.</p>
            <p>6.6 The financial liability of CT in connection with breach of the contract will be  limited to 500 euros. You will have the right to claim for damages only if CT has deliberately violated the contract. CT will not be liable for the actions or  inactions of the driver and will not be liable for damages that the driver causes  to the customer. </p>
            <p>6.7 You agree to fully indemnify and hold CT, their affiliate companies,  representatives, employees and directors harmless from any claims or losses  (including liabilities, damages, costs and expenses of any nature) that they suffer as a result of your use of the CT app (including the journeys you obtain  through your use of the CT app).
            </p>
            <p>6.8 CT may immediately end your use of the CT app if you breach these  General Terms and Conditions or we consider it necessary to protect the  integrity of CT or the safety of drivers. </p>
            <h5>7. Good practice using the CARGOTAXI app</h5>
            <p>7.1 As CT is not a provider or broker of the transport services, any issues with  defects or quality of the transport services will be resolved in accordance with  the rules and regulations of the transport service provider or the relevant  public authority.</p>
            <p>7.2 We ask to fill out a feedback form in the CT app. This enables us to offer  suggestions to the drivers for improving the quality of their service.  </p>
            <p>7.3 We expect that you use CT app in good faith and be respectful of the  drivers who offer their services through CT app. CT retains the right to close  your account if you have violated the terms set out in this General Terms and  Conditions or if your activities are malicious, i.e. withholding payment for the  provision of the transport service, fraud, being disrespectful towards the  drivers, etc. In these cases, your CT app account may be revoked without  prior notice.</p>
            <p>7.4 CT will make every effort to ensure that only drivers, who have integrity  and are respectful of their profession and customers, use the CT app.  However, we are in no position to guarantee that every provider of transport services, located by the CT app, satisfies the aforementioned criteria at all  times. If you experience objectionable transport service, please notify the  company responsible for the service, a supervisory authority or our customer  support.
            </p>
            <h5>8. Amendments to the General Terms  and Conditions</h5>
            <p>8.1 If any substantial amendments are made to the General Terms and  Conditions, then you will be notified by e-mail or CT app notifications. If you  continue using CT app, you will be deemed to accept the amendments.</p>
            <h5>9. Final Provisions</h5>
            <p>The General Terms and Conditions will be governed by and construed and  enforced in accordance with the laws of Republic of Austria. If the respective  dispute resulting from General Terms or Agreement could not be settled by  the negotiations, then the dispute will be finally solved in Handelsgericht in  Wien, Austria or Cargotaxi GmbH,Wien. If any provision of the General Terms  is held to be unenforceable, the parties will substitute for the affected  provision an enforceable provision that approximates the intent and economic  effect of the affected provision.
            </p>
            <p>Date of entry into force: 15.03.2021</p>
        </div>
    </section>
@stop
